name: pure_life
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-122.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  email_validator: ^2.1.17
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  go_router: ^13.2.0
  uuid: ^4.2.2
  get_it: ^7.6.7
  intl: ^0.19.0
  number_paginator: ^0.4.1
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1

  either_dart: ^1.0.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

 
  fonts:
    - family: BricolageGrotesque
      fonts:
        - asset: fonts/BricolageGrotesque-Regular.ttf
        - asset: fonts/BricolageGrotesque-SemiBold.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-Regular.ttf
         
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
